### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by happyTonakai** [SuperKevinZhang/rush_to_purchase#2]
请问如何安装呀，可以发布个release吗

**Comment by SuperKevinZhang** [comment]
还没开发完成，目前是需要chrome debug模式运行

**Comment by c55kai** [comment]
求求使用说明，debug模式也可以，想抢个手机

**Comment by yourscode** [comment]
大佬，像这样的问题怎么解决鸭  The page at 'https://item.jd.com/100012988188.html' was loaded over HTTPS, but requested an insecure resource 'http://cart.jd.com/cart_index'. This request has been blocked; the content must be served over HTTPS.

**Comment by yourscode** [comment]
> 还没开发完成，目前是需要chrome debug模式运行

大佬，像这样的问题怎么解决鸭 The page at 'https://item.jd.com/100012988188.html' was loaded over HTTPS, but requested an insecure resource 'http://cart.jd.com/cart_index'. This request has been blocked; the content must be served over HTTPS.

**Comment by EverSpeed** [comment]
可以继续帮忙更新一版吗，目前挂出来的好像出错了，是“unexpected token”错误。
